# Generated by Django 5.1.3 on 2024-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
